RHEcosystemAppEng/cluster-iq-console

src/app/services/api.js
=> Added API URL EnvVar

src/app/AccountDetails/AccountDetails.tsx, src/app/Accounts/Accounts.tsx, src/app/AppLayout/AppLayout.tsx, src/app/Overview/Overview.tsx, src/app/index.tsx, src/app/services/api.js, src/app/types/types.tsx
=> Accounts section

src/app/AccountDetails/AccountDetails.tsx, src/app/Accounts/Accounts.tsx, src/app/AppLayout/AppLayout.tsx, src/app/ClusterDetails/ClusterDetails.tsx, src/app/Clusters/Clusters.tsx, src/app/Overview/Overview.tsx, src/app/ServerDetails/ServerDetails.tsx, src/app/Servers/Servers.tsx, src/app/index.tsx, src/app/services/api.js, src/app/types/types.tsx
Related to this [PR](https://github.com/RHEcosystemAppEng/cluster-iq/pull/61)
=> Data refactor

package-lock.json, package.json
=> fix: Updated nodejs packages files

README.md
Signed-off-by: Vladimir Belousov <vbelouso@redhat.com>
=> updated GH repo URL in the quick-start guide

src/app/utils/parseFuncs.tsx
=> fix: update currency to USD

Makefile, src/app/ClusterDetails/ClusterDetails.tsx
Those changes are including the necessary changes to the clusters :
1. Relocated the Actions button  
2. Added a Divider 
3. The Dropdown code is in a separate component
=> feat: added action button to power on/power off cluster

src/app/Clusters/Clusters.tsx
=> fix: column sorting in the Clusters table

src/app/services/api.js
- Added 'dummy' API call to stop/start cluster
- Prettified the code according to formatter
=> feat: add dummy API calls for powering on/off cluster

src/app/AccountDetails/AccountDetails.tsx, src/app/ClusterDetails/ClusterDetails.tsx, src/app/ServerDetails/ServerDetails.tsx
- Remove `isWidthLimited` prop from PageSection components
- Fix visual whitespace issue on right side of page
Closes #49
=> fix: remove PageSection width constraints to eliminate UI gap

src/app/Accounts/Accounts.tsx, src/app/Accounts/types.ts
- Replace `useState/useEffect` filtering mechanism with `useMemo`
- Remove redundant `filteredData` state
=> feat: refactor Accounts page

package-lock.json, package.json, src/app/AppLayout/AppLayout.tsx, src/app/AppLayout/SidebarNavigation.tsx, src/app/Clusters/Clusters.tsx, src/app/Clusters/components/ClustersTable.tsx, src/app/Clusters/components/ClustersTableToolbar.tsx, src/app/Clusters/types.ts, src/app/Overview/constants.tsx, src/app/Servers/Servers.tsx, src/app/Servers/components/ServersTable.tsx, src/app/Servers/components/ServersTableToolbar.tsx, src/app/Servers/types.ts, src/app/index.tsx, src/app/types/types.tsx
- The new archive section for grouping Terminated clusters and instances in a separate menu.
- State management via URLs with nuqs
Related to #38
=> feat: add state management via URLs with nuqs

src/app/AppLayout/AppLayout.tsx
- Set the sidebar to open by default in desktop mode
- Set the sidebar to close when the window is resized
=> chore: manage sidebar state based on window width

src/app/Clusters/components/ClustersTable.tsx, src/app/Servers/components/ServersTable.tsx, src/app/components/common/TablesPagination.tsx, src/app/utils/tablePagination.ts
=> feat: add tables pagination

src/app/AppLayout/AppLayout.tsx, src/app/Contexts/UserContext.tsx, src/app/index.tsx
- Implemented `UserContext` to manage user details globally.
- Integrated `UserContext` into the application to ensure user details are accessible across components.
- Updated the application header to display user information.
=> feat: populate user details via UserContext

src/app/AccountDetails/components/AccountClusters.tsx
Hide terminated clusters from accounts view by default
=> feat: exclude terminated clusters from accounts view by default

src/app/Overview/Overview.tsx, src/app/Overview/hooks/useDashboardData.ts, src/app/services/api.js
Refactor the `Overview` page to reduce the number of API calls
=> chore: refactor overview page

package-lock.json, package.json, src/app/ClusterDetails/components/ClusterDetailsOverview.tsx, src/app/types/types.tsx
Includes changes on ClusterDetails page for displaying the new costs information included on this [PR](https://github.com/RHEcosystemAppEng/cluster-iq/pull/156)
=> feat: Added Cluster Costs info to Cluster details page

src/app/AccountDetails/components/AccountDescriptionList.tsx
=> Cluster count added to Account Details page

src/app/AppLayout/AppLayout.tsx
=> chore: update ClusterIQ title link to redirect to console overview page

src/app/AppLayout/AppLayout.tsx
=> feat: add user logout functionality

src/app/Overview/Overview.tsx, src/app/Overview/components/CardData.tsx, src/app/Overview/components/CardRenderer.tsx, src/app/Overview/hooks/useDashboardData.ts, src/app/Overview/types.ts
=> feat: add last scan date to overview page
